### ISSUE TITLE
more streamlined interface?

### ISSUE THREAD

**Issue by jwaldmann** [adamwalker/haskell_cudd#7]
(just a proposal)

I recently built this: https://gitlab.imn.htwk-leipzig.de/waldmann/min-comp-sort/blob/master/src/Bit.hs
using Implicit Parameters  ( https://ocharles.org.uk/blog/posts/2014-12-11-implicit-params.html) to hide the all-pervasive Manager. Indeed, I think this looks quite nice to me now: https://gitlab.imn.htwk-leipzig.de/waldmann/min-comp-sort/blob/master/src/Sort.hs

**Comment by adamwalker** [comment]
I have had a play with implicit parameters too and, like you say, it worked well.

However, they do not seem to be that well regarded by the Haskell community: https://www.reddit.com/r/haskell/comments/kbzjk/what_about_the_implicitparams_haskell_language/

Another alternative I have tried to avoid this problem is to use RecordWildCards. For example, see https://github.com/adamwalker/syntcomp.

I think it makes sense to provide another implicit parameter based interface to Cudd as another module in the library so that the user can choose whatever fits their tastes.

**Comment by jwaldmann** [comment]
Yes. I should rewrite my functions names to match this: https://hackage.haskell.org/package/ersatz-0.3.1/docs/Ersatz-Bit.html#t:Boolean . Do you have a suggestion on how to name the module and where to put it?

**Comment by jwaldmann** [comment]
see also #10

**Comment by adamwalker** [comment]
That looks like a sensible interface. I would call the module something like "Cudd.Implicit" if it uses implicit params. But, I'm boring and not good at thinking of names.

**Comment by jwaldmann** [comment]
I think I like https://github.com/jwaldmann/cudd-ersatz better now, and I'm gonna drop this implicit parameters idea.
